"""
Prometheus Metrics for JarvisCore v1.0.1.

Exposes counters, histograms, and gauges for:
- LLM usage (tokens, cost, duration per provider/model)
- Workflow execution (steps completed/failed, active counts)
- Event emission (trace events by type)

Ported from IA's monitoring/metrics.py with improvements:
- Clean helper functions (record_llm_call, record_step_execution)
- Graceful degradation when prometheus_client is not installed

Usage:
    from jarviscore.telemetry.metrics import record_llm_call, record_step_execution

    record_llm_call(
        provider="anthropic", model="claude-opus-4-5",
        input_tokens=1500, output_tokens=800,
        cost=0.12, duration=2.3, success=True,
    )
"""

import logging

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Optional prometheus_client import — no-op stubs when not installed.
#
# This guard ensures `import jarviscore` never crashes for developers
# who haven't installed prometheus-client.  When the package IS
# installed (e.g. pip install "jarviscore-framework[prometheus]"),
# full metric collection works transparently.
# ------------------------------------------------------------------

try:
    from prometheus_client import Counter, Gauge, Histogram
    _PROMETHEUS_AVAILABLE = True
except ImportError:
    _PROMETHEUS_AVAILABLE = False

    class _NoOpMetric:
        """Silent no-op that accepts any Counter/Histogram/Gauge call."""
        def __init__(self, *args, **kwargs):
            pass
        def labels(self, **kwargs):
            return self
        def inc(self, amount=1):
            pass
        def dec(self, amount=1):
            pass
        def observe(self, amount):
            pass

    Counter = Histogram = Gauge = _NoOpMetric  # type: ignore[assignment,misc]
    logger.debug(
        "prometheus-client not installed; metrics are no-ops. "
        "Install with: pip install 'jarviscore-framework[prometheus]'"
    )


# ------------------------------------------------------------------
# LLM Metrics
# ------------------------------------------------------------------

llm_tokens_input = Counter(
    "jarviscore_llm_tokens_input_total",
    "Total input tokens consumed by LLM calls",
    ["provider", "model"],
)

llm_tokens_output = Counter(
    "jarviscore_llm_tokens_output_total",
    "Total output tokens generated by LLM calls",
    ["provider", "model"],
)

llm_cost_dollars = Counter(
    "jarviscore_llm_cost_dollars_total",
    "Total cost in USD for LLM API calls",
    ["provider", "model"],
)

llm_request_duration = Histogram(
    "jarviscore_llm_request_duration_seconds",
    "LLM API request duration in seconds",
    ["provider", "model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0],
)

llm_requests_total = Counter(
    "jarviscore_llm_requests_total",
    "Total number of LLM API requests",
    ["provider", "model", "status"],
)


# ------------------------------------------------------------------
# Workflow / Step Metrics
# ------------------------------------------------------------------

workflow_steps_total = Counter(
    "jarviscore_workflow_steps_total",
    "Total workflow steps processed",
    ["status"],
)

step_execution_duration = Histogram(
    "jarviscore_step_execution_duration_seconds",
    "Step execution duration in seconds",
    ["status"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0],
)

active_workflows = Gauge(
    "jarviscore_active_workflows",
    "Number of currently active workflows",
)

active_steps = Gauge(
    "jarviscore_active_steps",
    "Number of currently executing steps",
)


# ------------------------------------------------------------------
# Event Metrics
# ------------------------------------------------------------------

events_emitted_total = Counter(
    "jarviscore_events_emitted_total",
    "Total trace events emitted",
    ["event_type"],
)


# ------------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------------

def record_llm_call(
    provider: str,
    model: str,
    input_tokens: int,
    output_tokens: int,
    cost: float,
    duration: float,
    success: bool,
) -> None:
    """
    Record a complete LLM call with all metrics.

    Args:
        provider: LLM provider (e.g. "anthropic", "openai")
        model: Model name (e.g. "claude-opus-4-5")
        input_tokens: Number of input/prompt tokens
        output_tokens: Number of output/completion tokens
        cost: Cost in USD
        duration: Duration in seconds
        success: Whether the call succeeded
    """
    llm_tokens_input.labels(provider=provider, model=model).inc(input_tokens)
    llm_tokens_output.labels(provider=provider, model=model).inc(output_tokens)
    llm_cost_dollars.labels(provider=provider, model=model).inc(cost)
    llm_request_duration.labels(provider=provider, model=model).observe(duration)
    status = "success" if success else "error"
    llm_requests_total.labels(provider=provider, model=model, status=status).inc()


def record_step_execution(
    duration: float,
    status: str,
) -> None:
    """
    Record step execution metrics.

    Args:
        duration: Execution duration in seconds
        status: Step outcome (e.g. "completed", "failed")
    """
    workflow_steps_total.labels(status=status).inc()
    step_execution_duration.labels(status=status).observe(duration)


def record_event(event_type: str) -> None:
    """Record a trace event emission."""
    events_emitted_total.labels(event_type=event_type).inc()


def increment_active_workflows() -> None:
    """Increment active workflow gauge."""
    active_workflows.inc()


def decrement_active_workflows() -> None:
    """Decrement active workflow gauge."""
    active_workflows.dec()


def increment_active_steps() -> None:
    """Increment active step gauge."""
    active_steps.inc()


def decrement_active_steps() -> None:
    """Decrement active step gauge."""
    active_steps.dec()


def start_prometheus_server(port: int = 9090) -> None:
    """Start the Prometheus metrics HTTP server."""
    if not _PROMETHEUS_AVAILABLE:
        logger.warning(
            "Cannot start Prometheus server: prometheus-client not installed. "
            "Install with: pip install 'jarviscore-framework[prometheus]'"
        )
        return
    from prometheus_client import start_http_server
    try:
        start_http_server(port)
        logger.info(f"Prometheus metrics server started on port {port}")
    except OSError as e:
        logger.warning(f"Failed to start Prometheus server on port {port}: {e}")
